parses revenue value
msohailhussain/python-sdk pull request #5
Opened 2018-03-15 13:28 UTC by rashidsp

2018-03-16 07:26 UTC, oakbani requested changes
Please do the following changes. 
Thanks.

2018-03-16 07:26 UTC, oakbani commented on optimizely/helpers/event_tag_utils.py
> +    logger: Optional logger.
Optional?

2018-03-16 07:26 UTC, oakbani commented on optimizely/helpers/event_tag_utils.py
> +      - Any values that cannot be cast to a float (e.g., an array or dictionary)
Misguiding comments. Please put ruby/php comments here in Python style

2018-03-16 07:26 UTC, oakbani commented on optimizely/helpers/event_tag_utils.py
> +    logger.log(enums.LogLevels.DEBUG, 'Event tags is not a hash.')
is not a dict.

2018-03-16 07:26 UTC, oakbani commented on optimizely/helpers/event_tag_utils.py
> +    logger.log(enums.LogLevels.WARNING, 'Revenue value is boolean.')
You can eliminate boolean condition with this below:
if type(whatever) in (float, int):
    # Do stuff.

2018-03-16 07:26 UTC, oakbani commented on optimizely/helpers/event_tag_utils.py
> +    logger.log(enums.LogLevels.WARNING, 'Revenue value is not an integer or float, or is not a numeric string.')
When you are throwing separate error for 'not a numeric string'. You can change this to
'Revenue value is not an integer or float or a string.'

2018-03-16 07:26 UTC, oakbani commented on optimizely/helpers/event_tag_utils.py
> +  logger.log(enums.LogLevels.INFO, 'Parsed revenue value "%s" from event tags.' % raw_value)
Convert raw_value to int before this line. So that this message prints the final value as an int and not as a string or float

2018-03-16 07:26 UTC, oakbani commented on tests/helpers_tests/test_event_tag_utils.py
> +  def test_get_revenue_value__revenue_tag_zero(self):
Why a separate test for 0 value? Looks like 0 is a special test case. You can merge these into above valid revenue tag method

2018-03-16 07:26 UTC, oakbani commented on tests/helpers_tests/test_event_tag_utils.py
> +    self.assertIsNone(event_tag_utils.get_numeric_value(None, logger=logger.SimpleLogger()))
Please also assert log messages for all numeric test cases as well

2018-03-16 07:26 UTC, oakbani commented on tests/test_event_builder.py
> +  def test_create_conversion_event__with_valid_string_revenue_event_tags(self):
This test case was written to check invalid scenario. Please don't change the intent. 
Instead give an invalid revenue value instead of '4200'

2018-03-16 07:26 UTC, oakbani commented on tests/test_optimizely.py
> +            'revenue': 4200,
Same as above comment

2018-03-16 14:00 UTC, rashidsp commented on optimizely/helpers/event_tag_utils.py
> +      - Any values that cannot be cast to a float (e.g., an array or dictionary)
Added from ruby.

2018-03-19 12:01 UTC, oakbani reviewed
Looks good. Jut avoid code repetition

2018-03-19 12:01 UTC, oakbani commented on tests/helpers_tests/test_event_tag_utils.py
> +        mock.call(enums.LogLevels.DEBUG, 'Event tags is not a dictionary.'),
You can easily avoid all this repetition by assigning string or mock.call values to a variable

2018-03-19 14:39 UTC, closed without merging

2018-03-19 14:39 UTC, rashidsp commented
Closing it: PR sent to Optimizely.